### PR TITLE
Dockerfile so that ProTECT versions can be validated in Dockstore (re…

### PR DESCRIPTION
**Pull request by wshands**
…solves issue #223)

Dockerfile so that ProTECT versions can be validated in Dockstore

### CODE REVIEW

**Comment by wshands** [comment]
Hi Arjun @arkal here is the Dockerfile

**Comment by arkal** [comment]
Commit message too long and improperly grammaticized. See https://chris.beams.io/posts/git-commit/

```
Add Dockerfile to base directory (resolves #223)


Dockstore validation requires a Dockerfile in the base directory of the 
repository. 

```

**Comment by wshands** [comment]
Hi @arkal Arjun,
The Dockerfile pull request is ready for your review.

**Comment by arkal** [comment]
It was faster for me to do it.

**Pull request closed without merging**
