### PR TITLE
Improve Docker output structure

### PR DESCRIPTION
**Pull request by cket**
Changes the output structure as discussed and updates the CWL output bindings correspondingly.

### CODE REVIEW

**Comment by cket** [comment]
jenkins, test this please

**Comment by cket** [comment]
jenkins, test this please

**Comment by cket** [comment]
@arkal ready to merge!

**Comment by cket** [comment]
Thanks! I set up a quay trigger in preparation of adding protect to Dockstore. You might see a notification about a new SSH key being added

**Comment by arkal** [comment]
will look out for it

**Pull request merged**
