### PR TITLE
Fix CWL descriptor and dockstore support (resolves #207)

### LINKED ISSUE #207: Protect CWL descriptor fixes
The current cwl descriptor [https://github.com/BD2KGenomics/protect/blob/master/docker/protect.cwl](url) has syntax errors and doesn't support optional arguments.

### PR DESCRIPTION
**Pull request by tboser**
resolves #207

### CODE REVIEW

**Comment by tboser** [comment]
@wshands @arkal

**Comment by wshands** [comment]
The tag changes look correct. Maybe we don't need to push the tag with the commit hash, e.g. docker push ${name}:${tag}, but I guess it is OK. 

Are the inputs listed in the CWL that are optional, those with the '?',  actually optional? If so it looks OK to me.

**Comment by arkal** [comment]
@tboser can you confirm every optional field is one you found in defaults.yaml?

**Comment by tboser** [comment]
Yes they're all in defaults.yaml.
@wshands you can see all the fields I've made optional can be found in https://github.com/BD2KGenomics/protect/blob/master/src/protect/pipeline/defaults.yaml

**Comment by wshands** [comment]
Ok then lets merge this

**Comment by wshands** [comment]
@tboser Thomas would you point me to a parameterized json input file I can use to quickly do a test run of ProTECT in my development dcc-ops setup?

**Comment by arkal** [comment]
@tboser , next time create a branch on your repo off the latest master called issues/XXX-description, then push to origin and PR from there.

**Pull request merged**
